version: '3'
volumes:
  pg_data:
    driver: local
services:
  postgres:
    container_name: keycloak-db
    image: postgres:13.7-alpine3.16
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes: 
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  keycloak:
    container_name: keycloak-app
    image: quay.io/keycloak/keycloak:19.0.1
    environment:
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      # KC_DB_URL: jdbc:postgresql://localhost:5432/postgres
      # jdbc:postgresql://{host}[:{port}]/[{database}]
      KC_DB_URL_DATABASE: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
    entrypoint: /opt/keycloak/bin/kc.sh start-dev
    ports:
      - 8080:8080
    depends_on:
      - postgres
